version: 0.2

phases:
  install:
    commands:
      - echo "No dependencies to install for a static HTML site"
      - pip install awscli
  pre_build:
    commands:
      - echo "No pre-build steps required for a static HTML site"
  build:
    commands:
      - echo "No build steps required for a static HTML site"
  post_build:
    commands:
      - echo Build completed on `date`
      - aws s3 cp index.html s3://secure-website-artifacts-naveed/index.html --content-type text/html
      - aws s3 cp other-file.html s3://secure-website-artifacts-naveed/other-file.html --content-type text/html
      - aws s3 cp css/ s3://secure-website-artifacts-naveed/css/ --recursive --content-type text/css
      - aws s3 cp js/ s3://secure-website-artifacts-naveed/js/ --recursive --content-type application/javascript
artifacts:
  files:
    - '**/*'
  discard-paths: yes
