version: 0.2

phases:
  install:
    commands:
      - echo Installing AWS CLI
      - pip install awscli
  build:
    commands:
      - echo Build started on `date`
  post_build:
    commands:
      - echo Build completed on `date`
      - aws s3 sync . s3://secure-website-artifacts-naveed/ --exclude "*" --include "*.html" --content-type "text/html"
      - aws s3 sync . s3://secure-website-artifacts-naveed/ --exclude "*" --include "*.css" --content-type "text/css"
      - aws s3 sync . s3://secure-website-artifacts-naveed/ --exclude "*" --include "*.js" --content-type "application/javascript"
      - aws s3 sync . s3://secure-website-artifacts-naveed/ --exclude "*" --include "*.jpg" --content-type "image/jpeg"
      - aws s3 sync . s3://secure-website-artifacts-naveed/ --exclude "*" --include "*.png" --content-type "image/png"

artifacts:
  files:
    - '**/*'
