version: 0.2

phases:
  install:
    commands:
      - echo "No dependencies to install for a static HTML site"
  pre_build:
    commands:
      - echo "No pre-build steps required for a static HTML site"
  build:
    commands:
      - echo "No build steps required for a static HTML site"
artifacts:
  files:
    - '**/*'
  discard-paths: yes
